### ISSUE TITLE
how does this work? (SOLVED)

### ISSUE THREAD

**Issue by SatanaDesigns** [Dorkerdotcom/Rate-my-avatar-screenshare-#1]
how do i run this?

**Comment by Dorkerdotcom** [comment]
Hello! Sorry for late reply. Heres a tutorial!
Github cant upload cus of the size.
Also i swear if u claim it its ur script ur a fucking skid.
https://anonfiles.com/Y8w0v1Pey4/2022-12-30_16-23-35_mp4

**Comment by SatanaDesigns** [comment]
why would i claim this as my own? i dont even do lua 😭

**Comment by Dorkerdotcom** [comment]
heres a made up story:
skid: find this
skid: uses it and claims he made it
ye
